      - name: Instalar postgresql-client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Aplicar migraciones
        run: |
          PGPASSWORD=evidence_dev_only psql -h localhost -U evidence -d evidence_test -f migrations/0001_init_orders.sql
          PGPASSWORD=evidence_dev_only psql -h localhost -U evidence -d evidence_test -f migrations/0002_init_payment_events.sql
